@extends('layouts.app')

@section('title', 'KejaPad Building Vibe')
@section('body_class', 'vibe-page')

@section('content')
<main class="page">
  <section class="hero-copy"><div><div class="eyebrow">Anonymous community feedback</div><h1>Catch problems before fights.</h1><p class="lead">Tenants can quietly flag building-wide issues. When three or more tenants report the same thing, the landlord gets a high-priority alert with pattern evidence.</p></div><div class="trust-strip"><div><strong>{{ optional($feedback->first())->total ?? 0 }}</strong><span>Top issue flags</span></div><div><strong>3+</strong><span>Alert trigger</span></div><div><strong>Anon</strong><span>Protected</span></div></div></section>
  <section class="page-panel"><div class="panel-head"><div><h2>Building Vibe</h2><p>{{ $property->name ?? 'Property' }} - anonymous tenant pulse</p></div><div class="status-pill">{{ $feedback->where('total', '>=', 3)->count() }} urgent alert</div></div><div class="content-grid"><article class="module wide"><div class="vibe-grid">@foreach ($feedback as $item)<div class="vibe {{ $item->total >= 3 ? 'alert' : '' }}"><strong>{{ $item->category }}</strong><span>{{ $item->total }} tenants flagged - {{ $item->total >= 3 ? 'urgent landlord alert sent' : 'monitoring' }}</span></div>@endforeach</div></article><article class="module"><div class="module-head"><div><h3>Flag an issue</h3><p>Submit anonymously.</p></div></div><form method="POST" action="{{ route('building-vibe.store') }}" class="list">@csrf<input type="hidden" name="category" value="Water pressure"><input type="hidden" name="fingerprint" value="water-low"><div class="field"><label for="message">What is happening?</label><div class="input-wrap"><input id="message" name="message" value="Low water pressure today" required></div></div><button class="mini-btn good" type="submit">Submit anonymous flag</button></form></article><article class="module"><div class="module-head"><div><h3>Landlord alert</h3><p>Only patterns become urgent.</p></div></div>@foreach ($feedback->where('total', '>=', 3) as $alert)<div class="item"><b>{{ $alert->category }}</b><span>High priority</span></div>@endforeach</article></div></section>
</main>
@endsection
